### ISSUE TITLE
trouble with webserver

### ISSUE THREAD

**Issue by maracasas** [chaosloth/Connotron_DMX_Gateway#1]
greetings.

i successfully compiled this file:
https://github.com/chaosloth/Connotron_DMX_Gateway/blob/master/ESP32_ArtNet_DMX_Gateway/ESP32_ArtNet_DMX_Gateway.ino

i see the esp32 is receiving artnet data, so i assume the device and bin works as intended

but for dear life, i can not access the webserver

i tried using the ip that m router give to the esp32, and the host name that shows in serial printer on arduino ide.

can you point me where is the problem please?

i am using all the libraries you shared + ESPAsyncWebServer from the same author of ESPAsync_WiFiManager

**Comment by chaosloth** [comment]
Hey @maracasas sorry to hear it's not working, can you send me some additional info to help debug, e.g.

- What board are you using?
- Can you add the serial output upon startup?
- Can you ping the <whatever>.local mDNS name?
- Can you telnet to the IP/DNS on port 80?

**Comment by maracasas** [comment]
it was a silly mistake on my end, i did not understand how the double reset was working, i could access the webserver for the 1st time (and add credentials/configure artnet there) but i could not access the webserver after that (without the double reset).

but if i understand the webserver is only for ota updates right? it is not for artnet configuration?

tell me, do you know if it is possible to change the "dmx in"  interface to another dmx out?
i am interested in doing that, that would be my homework though, but i would like to know if it is possible before crashing to  a wall ( i need 2 dmx universes and i would like to test this  concept)

**Comment by chaosloth** [comment]
Cool glad it worked out. You're right it is only used for OTA, you could of course roll your own web interface and call api end points to configure it.

As for changing the DMX (IN/OUT) yes this is certainly possible, you can also add more DMX interfaces, so long as you have free UARTS.

Aside note, I have a bunch of left over boards (Prototype 2). I'm happy to send you a couple. Direct message me on LinkedIn and I'll send them to you (no charge) https://www.linkedin.com/in/christopherjamesconnolly

**Comment by rvbcrs** [comment]
@maracasas @chaosloth Hi, I'm also trying to compile the ino file, but I tried in PlatformIO and in Arduino IDE and both gave me a massive amount of errors! Can you tell me how to compile this?

**Comment by DeverosTV** [comment]
> @maracasas @chaosloth Hi, I'm also trying to compile the ino file, but I tried in PlatformIO and in Arduino IDE and both gave me a massive amount of errors! Can you tell me how to compile this?

yes i think the biggest issue you have with arduino ide, is that you updated the esp32 board to the latest version. that gave me errors or the board was not working.

right now i am using esp32 version 2.0.9 from espresiff
also aside from the libraries that are mentioned in the  main page i am also using ESPAsyncWebServer from the same author of ESPAsync_WiFiManager

it should be compiling after those changes, at least mine are

**Comment by chaosloth** [comment]
> @maracasas @chaosloth Hi, I'm also trying to compile the ino file, but I tried in PlatformIO and in Arduino IDE and both gave me a massive amount of errors! Can you tell me how to compile this?

Hey mate - can you pls open a new issue for this and give the output that you see. 

I've been building using Platform.IO for the most recent builds, keen to see what you're getting 

I'm going to close this issue as the OP has indicated it's resolved
